version: '3'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    volumes:
      - ./data:/bitnami/redis/data/

    image: 'gcr.io/gowish/redis-graph:0.0.2'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=str0ng_passw0rd
    command:
      - /opt/bitnami/redis/bin/redis-server
      - "--requirepass"
      - str0ng_passw0rd
      -  "--masterauth"
      - str0ng_passw0rd
      - "--loadmodule"
      - "/usr/lib/redis/modules/redisgraph.so"  
      - "--dir"
      - "/bitnami/redis/data"
      - "--appendonly"
      - "yes"
    
    networks:
      - app-tier
    ports:
      - '6379:6379'
  redis-sentinel:
    image: 'docker.io/bitnami/redis-sentinel:7.0.4-debian-11-r20'
    environment:
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
      - REDIS_PASSWORD=str0ng_passw0rd
    depends_on:
      - redis
    ports:
      - '26379:26379'
    networks:
      - app-tier